### ISSUE TITLE
Kontrakttest for fdk-informationmodel-harvester

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-informationmodel-harvester#11]
Ta utgangspunkt i
a-frontend-service
a-backend-service

og verifiser at de ulike tjenestene har en specc fil.
Deretter skal vi skrive kontrakttester/featuretester for den enkelte tjenesten.

Implementere kontrakttest/featurestest for tjenesten:
fdk-informationmodel-harvester

**Comment by NilsOveTen** [comment]
Løst av https://github.com/Informasjonsforvaltning/fdk-informationmodel-harvester/issues/46
