### ISSUE TITLE
Muliggjør høsting av tomme kataloger

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-informationmodel-harvester#142]

**Comment by NilsOveTen** [comment]
@KurtStian jeg klarer ikke å gjenskape dette, kan du gi meg et eksempel på en katalog dette feiler for?

**Comment by KurtStian** [comment]
> @KurtStian jeg klarer ikke å gjenskape dette, kan du gi meg et eksempel på en katalog dette feiler for?
@NilsOveTen 
Har testet i staging og høsting av tomme kataloger ser nå ut til å fungere. Brukte følgende filer:
Fil som har katalog og 2 modeller: https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-testdata/master/testdata/test_ksf.ttl
Fil for fjerning av de 2 modellene (satte kun # foran egenskapen "modelldcatno:model": https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-testdata/master/testdata/test_ksf_slett.ttl

Vet ikke når dette ble OK. Men tidligere feilet det både med hashtag foran egenskapen og når egenskapen var slettet fra filen.

**Comment by NilsOveTen** [comment]
Huh, jaja. Jeg lukker denne saken som løst og så får du gi beskjed om noe lignende skjer igjen
