### ISSUE TITLE
Virksomhetsfilter til informasjonsmodeller viser ikke organisasjoner lenger

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-informationmodel-harvester#31]
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/b96dad6d-e8dc-4579-8176-75af90f5daf0)

Skal vises på lik linje som datasett

**Comment by azaxarov** [comment]
Ser ikke ut som et problem i staging. Det var muligens at en av APIene ikke svarte i rimelig tid.

**Comment by oyvindis** [comment]
Aggregering orgPath har key 'STAT/xx' og ikke med prefix skråstrek '/STAT/xx'. @NilsOveTen er det pga. gammel organization-endepunkt og vil bli rettet i høsting?

**Comment by lillelars** [comment]
fungerer korrekt. Lukker saken.
