### ISSUE TITLE
Høsting av modeller - '*' godtas ikke som verdi for maxOccurs

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/fdk-informationmodel-harvester#48]
Høstingen av Kartverkets modeller feilet siden de har brukt * som maxOccurs. 

[Spesifikasjonen for informasjonsmodeller](https://github.com/Informasjonsforvaltning/dcat-no-info/blob/master/ontology/dcatno_informationModel_en.owl) tar høyde for dette, :
![image](https://user-images.githubusercontent.com/17720749/78017011-ec27e380-734b-11ea-83a4-19349e89b4d7.png)

maxOccurs kan enten være en nonNegativInteger eller ha verdien'*'

Det må fikses slik at løsningen godtar *.

**Comment by azaxarov** [comment]
@lillelars Er denne issue fortsatt relevant?

**Comment by ToHelland** [comment]
Denne skal være i orden.

**Comment by lillelars** [comment]
Testet av Tore. Lukker saken.
