### ISSUE TITLE
Resterende oppgaver knyttet til publisering av informasjonsmodeller

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-informationmodel-harvester#62]
- [x] Dele opp hele Altinn katalogen til 3 ulike turtle modell-kataloger:
(skille på tre typer SERES, OR, Altinn)

- [x] Plukke opp enumerations. Se:
 https://staging.fellesdatakatalog.digdir.no/informationmodels/2102a74a-7585-37fd-8a1d-a4044de9b76e
"<xs:enumeration value="januar-februar2020" />
            <xs:enumeration value="november-desember2019" />
            <xs:enumeration value="september-oktober2019" />"

- [x] fraDato // tilDato fra lenke:
https://www.altinn.no/api/metadata/formtask/5645/1/forms/1/8/xsd
<xs:complexType name="Tidsperiode">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="1" name="fraDato" type="Dato" nillable="true" />
            <xs:element maxOccurs="1" minOccurs="1" name="tilDato" type="Dato" nillable="true" />

- [x] Høsteren må håndtere SERES-katalogen

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/107225448-14c34400-6a19-11eb-9a90-48a2e6374bf6.png)
![image](https://user-images.githubusercontent.com/73637969/107225459-1a208e80-6a19-11eb-9325-97827a21b11b.png)
